keys:
  - &t470 age12pydm6u896tacezn84kvlz9sugwrqdptua0qxd4vkrv50gtzqd9shdgfzx
  - &pub_t470 age143su32y0xfp5peq98f57pv9v9qup67ugd2pyse4mcneh2ah6pszqv8gqug
  - &macbook age1slhdu0svdar7am5z3j7ywd9w64uay9uruqgxhgu7lzr3rerg6vjs67xnlv
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *t470
      - *pub_t470
      - *macbook

